baseURL = "http://example.org/"
languageCode = "en-us"
title = "Timer | Eagle IO"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Main"
url     = "main"
weight  = 2
[[menu.main]]
name    = "About"
url     = "about"
weight  = 3
[[menu.main]]
name    = "Who we are"
url     = "who"
weight  = 4
[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 5

# Site Params
[params]
home = "Home"
logo = "images/eagleio2.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "Eagle I/O Consultant"
description = "STUDENT LED CONSULTING GROUP"


# flip text
[[params.banner.flipText]]
title   = "Student"
[[params.banner.flipText]]
title   = "Consultant"
[[params.banner.flipText]]
title   = "Innovator"


# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"