baseURL = "http://example.org/"
languageCode = "en-us"
title = "Timer | Responsive Multipurpose Bootstrap Hugo Template"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Main"
url     = "main"
weight  = 2
[[menu.main]]
name    = "About"
url     = "about"
weight  = 3
[[menu.main]]
name    = "Who we are"
url     = "who"
weight  = 4
[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 5


# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "Eagle IO"
description = ""
# button
btn     = true
btnText = "Download More"
btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "Student"
[[params.banner.flipText]]
title   = "Consultatn"
[[params.banner.flipText]]
title   = "Innovator"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT ME"
content = "Student Led Consultant""
image   = "images/about/about.jpg"

# Call to Action
[params.cta]
enable  = true
title   = "Eagle IO"
content = ""
btnText = "Contact with me"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"

