baseurl = "/"
languageCode = "en-us"
title = "Eagle IO"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[[menu.main]]
    name = "Main"
    url = "/main/"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Alumni"
    url = "/Alumni/"
[[menu.main]]
    name = "Contact Us"
    url = "/contact/"

[params]
    description = "Eagle IO Blogdown"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "eagleio2.png"
    width = 50
    height = 50
    alt = "Logo"

